// AbName

export const SET_ALL_DB_USER = 'SET_ALL_DB_USER';
export const SET_ALL_SHIPPING_INFO = 'SET_ALL_SHIPPING_INFO';
export const SET_ALL_SHIPPING_TERM = 'SET_ALL_SHIPPING_TERM';
export const SET_ALL_ABNAME_CATEGORY = 'SET_ALL_ABNAME_CATEGORY';
